### ISSUE TITLE
any planning porting to KF5

### ISSUE THREAD

**Issue by sadhen** [fhackenberger/ktikz#4] opened 2016-02-15 10:27 UTC

**Comment by fhackenberger** [comment] 2016-02-15 12:54
Not at the moment, patches are welcome, of course!

**Comment by sadhen** [comment] 2016-02-16 13:09
after I post the issue, I find https://github.com/jfmcarreira/ktikz. It seems to be a kf5 port.

**Comment by sadhen** [comment] 2017-08-20 14:53
I will try to find out what I can help the next weekend.

**Comment by fhackenberger** [comment] 2017-09-21 10:55
Duplicate of #8

**Closed by fhackenberger** 2017-09-21 10:55 UTC
