### ISSUE TITLE
KtikZ inserts text after EOF

### ISSUE THREAD

**Issue by genodeftest** [fhackenberger/ktikz#30] opened 2018-07-10 22:10 UTC
Quite often when saving a tikz file from KtikZ, it inserts text after the end of the document.

Simplified example document, content before opening the document with KtikZ and also how it is being displayed in KTikZ:
```
\begin{tikzpicture}
    \draw (0, 0) -- (0, 1);
\begin{tikzpicture}
```

When saving the document using KTikZ, it is modified in a way that starting from some point in the document, any text is written to disk twice. Example file on disk:
```
\begin{tikzpicture}
    \draw (0, 0) -- (0, 1);
\begin{tikzpicture}
aw (0, 0) -- (0, 1);
\begin{tikzpicture}
```

I'm using these software versions on Fedora 28:
ktikz-0.12-2.fc28.x86_64
qt5-qtbase-5.10.1-6.fc28.x86_64
kf5-kio-core-libs-5.47.0-2.fc28.x86_64
tex-preview-12.1-4.fc28.noarch
glibc-2.27-19.fc28.x86_64

**Comment by jfmcarreira** [comment] 2018-07-11 00:34
Thanks for the feedback.
This happen in the past I thought I fixed it. I think it might be KF5 porting issues.

**Comment by bonanza123** [comment] 2019-02-07 17:09
I can confirm that this bug still exists

**Comment by sdnr** [comment] 2019-02-27 10:15
> I can confirm that this bug still exists in v0.12

Me too

**Comment by AndreaDiPietro92** [comment] 2019-09-24 13:40
> I can confirm that this bug still exists in v0.12

Me too

Kubuntu 19.04
Ktikz : 0.12
KDE Frameworks 5.62.0
Qt 5.12.2 (compilato con 5.12.2)

**Comment by SBasalaev** [comment] 2019-10-22 08:44
The file simply does not get truncated. If you remove something from the file and save it you can see that its size does not change. If you reopen it then, there will be garbage from the old version after the supposed end of file.

**Comment by jfmcarreira** [comment] 2020-02-11 17:59
I merged a PR which might fix this problem. Closing for now.

**Closed by jfmcarreira** 2020-02-11 17:59 UTC
Labels: bug

**Comment by youcann** [comment] 2020-11-25 17:49
Since this bug is in release 0.12, are you planning on releasing a new version soon?
I have this bug on all my machines running Ubuntu and Manjaro.

**Comment by jfmcarreira** [comment] 2020-11-25 17:53
Did you tried to build the "master" branch to see if the problem is solved?

**Comment by youcann** [comment] 2020-11-25 18:10
The bug only occurs sporadically in the 0.12 release (most often after i copied and pasted together several pgfplot files). The build of the current master seems to be fine. That's why i would love to see a release based on the current state.
